# Generated by Django 5.1.1 on 2024-10-14 21:27

import os
from django.db import migrations
from loguru import logger


def generate_superuser(apps, schema_editor):
    from django.contrib.auth import get_user_model

    username = os.environ.get("ADMIN_USERNAME")
    password = os.environ.get("ADMIN_PASSWORD")
    email = os.environ.get("ADMIN_EMAIL")

    user = get_user_model()

    if not user.objects.filter(username=username, email=email).exists():
        logger.info("Creating new superuser")
        admin = user.objects.create_superuser(
            username=username, password=password, email=email
        )
        admin.save()
    else:
        logger.info("Superuser already created!")


class Migration(migrations.Migration):
    dependencies = []

    operations = [
        migrations.RunPython(generate_superuser),
    ]
