services:
  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    env_file:
      - .env
    environment:
      - DOMAIN_URL
    ports:
      - "80:80"
    volumes:
      - ./etc/nginx/templates-initiate:/etc/nginx/templates
      - ./etc/letsencrypt:/etc/letsencrypt
      - ./certbot/data:/var/www/certbot


  certbot:
    container_name: certbot
    build:
      context: ./certbot
      dockerfile: Dockerfile
    depends_on:
      - nginx
    env_file:
      - .env
    environment:
      - DOMAIN_URL
      - DOMAIN_EMAIL
    command: >-
            certonly --reinstall --webroot --webroot-path=/var/www/certbot
            --email ${DOMAIN_EMAIL} --agree-tos --no-eff-email -d ${DOMAIN_URL}
    volumes:
      - ./etc/letsencrypt:/etc/letsencrypt
      - ./certbot/data:/var/www/certbot

