# Generated by Django 5.0.7 on 2024-09-08 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metering_unit', '0002_alter_address_city_alter_address_corp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meteringunit',
            name='service_organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mu_so', to='metering_unit.organization'),
        ),
    ]
