# Generated by Django 5.0.7 on 2024-09-18 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metering_unit', '0004_street_typestreet_region_address_region_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='latitude',
            field=models.FloatField(default=60),
        ),
        migrations.AddField(
            model_name='address',
            name='longitude',
            field=models.FloatField(default=30),
        ),
    ]
