# Generated by Django 5.0.7 on 2024-09-19 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metering_unit', '0006_remove_address_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='street_new',
        ),
        migrations.AlterField(
            model_name='address',
            name='street',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='metering_unit.street'),
        ),
        migrations.AlterField(
            model_name='street',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='street',
            name='type_street',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='metering_unit.typestreet'),
        ),
    ]
