# Generated by Django 5.0.7 on 2024-09-19 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metering_unit', '0007_remove_address_street_new_alter_address_street_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typestreet',
            name='fullname',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='typestreet',
            name='name',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
    ]
