# Generated by Django 5.0.7 on 2024-07-24 21:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("device", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ServiceOrganization",
            new_name="Organization",
        ),
        migrations.AlterField(
            model_name="meteringunit",
            name="customer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="metering_units_customer",
                to="device.customer",
            ),
        ),
        migrations.AlterModelOptions(
            name="organization",
            options={"verbose_name_plural": "organizations"},
        ),
        migrations.AlterField(
            model_name="meteringunit",
            name="service_organization",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="metering_units_service_organization",
                to="device.serviceorganization",
            ),
        ),
        migrations.DeleteModel(
            name="Customer",
        ),
    ]
