# Generated by Django 5.0.7 on 2024-08-12 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("device", "0002_address_tsorganization_remove_meteringunit_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="meteringunit",
            name="totem_number",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
