# Generated by Django 5.0.7 on 2024-08-12 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("device", "0004_alter_address_itp_alter_address_city_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="ITP",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="address",
            name="city",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="address",
            name="corp",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="address",
            name="house_number",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="address",
            name="liter",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="address",
            name="street",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
