# Generated by Django 5.0.7 on 2024-08-27 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0012_remove_address_itp_remove_organization_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeToRegistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device_type_file', models.CharField(max_length=100)),
                ('numbers_registry', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'types_to_registry',
            },
        ),
        migrations.RenameField(
            model_name='device',
            old_name='device_mod',
            new_name='mod',
        ),
        migrations.RemoveField(
            model_name='device',
            name='device_type',
        ),
        migrations.RemoveField(
            model_name='devicemod',
            name='type_devise',
        ),
        migrations.AddField(
            model_name='deviceverification',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='device',
            name='type_of_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='device.typetoregistry'),
        ),
    ]
