# Generated by Django 5.0.7 on 2024-08-28 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0013_typetoregistry_rename_device_mod_device_mod_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meteringunit',
            name='tso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='metering_units_tso', to='device.organization'),
        ),
        migrations.RemoveField(
            model_name='devicetype',
            name='registry_number',
        ),
        migrations.AddField(
            model_name='device',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='device.devicetype'),
        ),
        migrations.DeleteModel(
            name='TSOrganization',
        ),
    ]
