# Generated by Django 5.0.7 on 2024-08-28 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0014_alter_meteringunit_tso_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meteringunit',
            old_name='ITP',
            new_name='itp',
        ),
        migrations.AlterField(
            model_name='typetoregistry',
            name='device_type_file',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
