# Generated by Django 5.0.7 on 2024-08-29 22:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0015_rename_itp_meteringunit_itp_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='deviceverification',
            old_name='device_id',
            new_name='device',
        ),
        migrations.AlterField(
            model_name='device',
            name='factory_number',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='installation_point',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device', to='device.deviceinstallationpoint'),
        ),
        migrations.AlterField(
            model_name='device',
            name='metering_unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device', to='device.meteringunit'),
        ),
        migrations.AlterField(
            model_name='device',
            name='mod',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device', to='device.devicemod'),
        ),
        migrations.AlterField(
            model_name='device',
            name='registry_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device', to='device.deviceregistrynumber'),
        ),
        migrations.AlterField(
            model_name='device',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device', to='device.devicetype'),
        ),
        migrations.AlterField(
            model_name='device',
            name='type_of_file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device', to='device.typetoregistry'),
        ),
        migrations.AlterField(
            model_name='deviceinstallationpoint',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='devicemod',
            name='mod',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='deviceregistrynumber',
            name='registry_number',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='devicetype',
            name='type',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='deviceverification',
            name='verification_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='meteringunit',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mu_address', to='device.address'),
        ),
        migrations.AlterField(
            model_name='meteringunit',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mu_c', to='device.organization'),
        ),
        migrations.AlterField(
            model_name='meteringunit',
            name='service_organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mu_so', to='device.organization'),
        ),
        migrations.AlterField(
            model_name='meteringunit',
            name='tso',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mu_tso', to='device.organization'),
        ),
        migrations.AlterField(
            model_name='usertoorganization',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_to_org', to='device.organization'),
        ),
        migrations.AlterField(
            model_name='usertoorganization',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_to_org', to=settings.AUTH_USER_MODEL),
        ),
    ]
