# Generated by Django 5.0.7 on 2024-09-04 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0017_remove_meteringunit_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviceverification',
            name='verification_date',
            field=models.DateField(default='1900-01-01'),
        ),
    ]
