# Generated by Django 5.0.7 on 2024-09-08 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0018_alter_deviceverification_verification_date'),
        ('metering_unit', '0002_alter_address_city_alter_address_corp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='installation_point',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='device', to='device.deviceinstallationpoint'),
        ),
        migrations.AlterField(
            model_name='device',
            name='metering_unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='device', to='metering_unit.meteringunit'),
        ),
        migrations.AlterField(
            model_name='device',
            name='mod',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='device', to='device.devicemod'),
        ),
        migrations.AlterField(
            model_name='device',
            name='registry_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='device', to='device.deviceregistrynumber'),
        ),
        migrations.AlterField(
            model_name='device',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='device', to='device.devicetype'),
        ),
        migrations.AlterField(
            model_name='device',
            name='type_of_file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='device', to='device.typetoregistry'),
        ),
        migrations.AlterField(
            model_name='deviceverification',
            name='device',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='verifications', to='device.device'),
        ),
    ]
