# Generated by Django 5.1.1 on 2024-10-14 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("metering_unit", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeviceInstallationPoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "verbose_name_plural": "device_installation_points",
            },
        ),
        migrations.CreateModel(
            name="DeviceMod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("mod", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "verbose_name_plural": "device_mods",
            },
        ),
        migrations.CreateModel(
            name="DeviceRegistryNumber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("registry_number", models.CharField(max_length=10, unique=True)),
            ],
            options={
                "verbose_name_plural": "device_registry_numbers",
            },
        ),
        migrations.CreateModel(
            name="DeviceType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("type", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "verbose_name_plural": "device_types",
            },
        ),
        migrations.CreateModel(
            name="TypeToRegistry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("device_type_file", models.CharField(max_length=100, unique=True)),
                ("numbers_registry", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name_plural": "types_to_registry",
            },
        ),
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("factory_number", models.CharField(max_length=100, unique=True)),
                ("notes", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "metering_unit",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="device",
                        to="metering_unit.meteringunit",
                    ),
                ),
                (
                    "installation_point",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="device",
                        to="device.deviceinstallationpoint",
                    ),
                ),
                (
                    "mod",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="device",
                        to="device.devicemod",
                    ),
                ),
                (
                    "registry_number",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="device",
                        to="device.deviceregistrynumber",
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="device",
                        to="device.devicetype",
                    ),
                ),
                (
                    "type_of_file",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="device",
                        to="device.typetoregistry",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "devices",
            },
        ),
        migrations.CreateModel(
            name="DeviceVerification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("verification_date", models.DateField(default="1900-01-01")),
                ("valid_date", models.DateField(default="1900-01-01")),
                ("is_actual", models.BooleanField(default=False)),
                ("is_delete", models.BooleanField(default=False)),
                (
                    "device",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="verifications",
                        to="device.device",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "device_verifications",
            },
        ),
    ]
