# Generated by Django 5.1.4 on 2025-02-12 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [
        ("device", "0002_typetoregistryimport"),
        ("device", "0003_rename_deviceinstallationpoint_installationpoint_and_more"),
        ("device", "0004_siname_alter_installationpoint_options_and_more"),
        ("device", "0005_remove_device_name_si_device_si_name"),
        ("device", "0006_alter_installationpoint_options_and_more"),
        ("device", "0007_remove_device_si_name_typetoregistryimport_si_name_and_more"),
        ("device", "0008_remove_typetoregistryimport_si_name_and_more"),
        ("device", "0009_remove_device_type_of_file_and_more"),
    ]

    dependencies = [
        ("device", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="DeviceInstallationPoint",
            new_name="InstallationPoint",
        ),
        migrations.RenameModel(
            old_name="DeviceMod",
            new_name="Modification",
        ),
        migrations.RenameModel(
            old_name="DeviceRegistryNumber",
            new_name="RegistryNumber",
        ),
        migrations.RenameModel(
            old_name="DeviceType",
            new_name="TypeName",
        ),
        migrations.RenameModel(
            old_name="DeviceVerification",
            new_name="Verification",
        ),
        migrations.CreateModel(
            name="SIName",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100, unique=True)),
                ("order", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "verbose_name_plural": "si_names",
                "ordering": ["order"],
            },
        ),
        migrations.AlterModelOptions(
            name="installationpoint",
            options={
                "ordering": ["order"],
                "verbose_name_plural": "device_installation_points",
            },
        ),
        migrations.AddField(
            model_name="installationpoint",
            name="order",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="device",
            name="installation_point",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="devices",
                to="device.installationpoint",
            ),
        ),
        migrations.AlterField(
            model_name="device",
            name="metering_unit",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="devices",
                to="device.meteringunit",
            ),
        ),
        migrations.AlterField(
            model_name="device",
            name="registry_number",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="devices",
                to="device.registrynumber",
            ),
        ),
        migrations.AlterField(
            model_name="device",
            name="type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="devices",
                to="device.typename",
            ),
        ),
        migrations.AlterModelOptions(
            name="installationpoint",
            options={
                "ordering": ["order"],
                "verbose_name_plural": "installation_points",
            },
        ),
        migrations.AlterModelOptions(
            name="modification",
            options={"verbose_name_plural": "mods"},
        ),
        migrations.AlterModelOptions(
            name="registrynumber",
            options={"verbose_name_plural": "registry_numbers"},
        ),
        migrations.AlterModelOptions(
            name="typename",
            options={"verbose_name_plural": "types"},
        ),
        migrations.AlterModelOptions(
            name="verification",
            options={"verbose_name_plural": "verifications"},
        ),
        migrations.RemoveField(
            model_name="verification",
            name="is_delete",
        ),
        migrations.CreateModel(
            name="TypeToRegistryImport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("csv_file", models.FileField(upload_to="uploads/")),
                ("date_added", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name="typetoregistry",
            name="si_name",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="typetoreg",
                to="device.siname",
            ),
        ),
        migrations.RemoveField(
            model_name="device",
            name="type_of_file",
        ),
        migrations.RenameField(
            model_name="device",
            old_name="mod",
            new_name="modification",
        ),
        migrations.AlterField(
            model_name="device",
            name="modification",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="devices",
                to="device.modification",
            ),
        ),
        migrations.RenameField(
            model_name="modification",
            old_name="mod",
            new_name="modification",
        ),
        migrations.AddField(
            model_name="device",
            name="name",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="devices",
                to="device.siname",
            ),
        ),
        migrations.AddField(
            model_name="device",
            name="valid_date",
            field=models.DateField(default="1900-01-01"),
        ),
        migrations.AddField(
            model_name="modification",
            name="type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="modifications",
                to="device.typename",
            ),
        ),
        migrations.AddField(
            model_name="typename",
            name="name",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="types",
                to="device.siname",
            ),
        ),
        migrations.AddField(
            model_name="verification",
            name="is_published",
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name="TypeRegistry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "number_registry",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="types",
                        to="device.registrynumber",
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="numbers_registry",
                        to="device.typename",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "types_registry",
            },
        ),
        migrations.DeleteModel(
            name="TypeToRegistry",
        ),
    ]
