# Generated by Django 5.1.4 on 2025-02-03 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("device", "0002_typetoregistryimport"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="DeviceInstallationPoint",
            new_name="InstallationPoint",
        ),
        migrations.RenameModel(
            old_name="DeviceMod",
            new_name="Modification",
        ),
        migrations.RenameModel(
            old_name="DeviceRegistryNumber",
            new_name="RegistryNumber",
        ),
        migrations.RenameModel(
            old_name="DeviceType",
            new_name="TypeName",
        ),
        migrations.RenameModel(
            old_name="DeviceVerification",
            new_name="Verification",
        ),
    ]
