# Generated by Django 5.1.8 on 2025-06-18 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("device", "0002_alter_device_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="device",
            name="name",
        ),
        migrations.AlterField(
            model_name="verification",
            name="mit_notation",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="type"
            ),
        ),
        migrations.AlterField(
            model_name="verification",
            name="mit_number",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="registry_number"
            ),
        ),
        migrations.AlterField(
            model_name="verification",
            name="mit_title",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="device_title"
            ),
        ),
        migrations.AlterField(
            model_name="verification",
            name="org_title",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="verification_organization",
            ),
        ),
    ]
