# Generated by Django 5.1.4 on 2025-02-05 21:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("device", "0003_rename_deviceinstallationpoint_installationpoint_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SIName",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100, unique=True)),
                ("order", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "verbose_name_plural": "si_names",
                "ordering": ["order"],
            },
        ),
        migrations.AlterModelOptions(
            name="installationpoint",
            options={
                "ordering": ["order"],
                "verbose_name_plural": "device_installation_points",
            },
        ),
        migrations.AddField(
            model_name="device",
            name="name_si",
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="installationpoint",
            name="order",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="device",
            name="installation_point",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="devices",
                to="device.installationpoint",
            ),
        ),
        migrations.AlterField(
            model_name="device",
            name="metering_unit",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="devices",
                to="device.meteringunit",
            ),
        ),
        migrations.AlterField(
            model_name="device",
            name="mod",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="devices",
                to="device.modification",
            ),
        ),
        migrations.AlterField(
            model_name="device",
            name="registry_number",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="devices",
                to="device.registrynumber",
            ),
        ),
        migrations.AlterField(
            model_name="device",
            name="type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="devices",
                to="device.typename",
            ),
        ),
        migrations.AlterField(
            model_name="device",
            name="type_of_file",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="devices",
                to="device.typetoregistry",
            ),
        ),
    ]
