# Generated by Django 5.1.4 on 2025-02-05 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("device", "0004_siname_alter_installationpoint_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="device",
            name="name_si",
        ),
        migrations.AddField(
            model_name="device",
            name="si_name",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="devices",
                to="device.siname",
            ),
        ),
    ]
