# Generated by Django 5.1.4 on 2025-02-06 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("device", "0006_alter_installationpoint_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="device",
            name="si_name",
        ),
        migrations.AddField(
            model_name="typetoregistryimport",
            name="si_name",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="typetoreg",
                to="device.siname",
            ),
        ),
        migrations.AlterField(
            model_name="verification",
            name="is_published",
            field=models.BooleanField(default=False),
        ),
    ]
