# Generated by Django 5.1.4 on 2025-02-11 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("device", "0008_remove_typetoregistryimport_si_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="device",
            name="type_of_file",
        ),
        migrations.RenameField(
            model_name="device",
            old_name="mod",
            new_name="modification",
        ),
        migrations.RenameField(
            model_name="modification",
            old_name="mod",
            new_name="modification",
        ),
        migrations.AddField(
            model_name="device",
            name="name",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="devices",
                to="device.siname",
            ),
        ),
        migrations.AddField(
            model_name="device",
            name="valid_date",
            field=models.DateField(default="1900-01-01"),
        ),
        migrations.AddField(
            model_name="modification",
            name="type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="modifications",
                to="device.typename",
            ),
        ),
        migrations.AddField(
            model_name="typename",
            name="name",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="types",
                to="device.siname",
            ),
        ),
        migrations.AlterField(
            model_name="verification",
            name="is_published",
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name="TypeRegistry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "number_registry",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="types",
                        to="device.registrynumber",
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="numbers_registry",
                        to="device.typename",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "types_registry",
            },
        ),
        migrations.DeleteModel(
            name="TypeToRegistry",
        ),
    ]
