# Generated by Django 5.1.4 on 2025-03-03 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "device",
            "0002_typetoregistryimport_squashed_0009_remove_device_type_of_file_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="verification",
            old_name="mi_mitype",
            new_name="mit_notation",
        ),
        migrations.RenameField(
            model_name="verification",
            old_name="mit_mitnumber",
            new_name="mit_number",
        ),
        migrations.RenameField(
            model_name="verification",
            old_name="mi_mititle",
            new_name="mit_title",
        ),
    ]
