# Generated by Django 5.1.4 on 2025-03-05 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("device", "0010_rename_mi_mitype_verification_mit_notation_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="attention",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="meteringunit",
            name="attention",
            field=models.BooleanField(default=False),
        ),
    ]
