# Generated by 'django-admin startproject' using Django 5.0.7.
import logging
import os
import sys
from pathlib import Path

import rest_framework.authentication
from django.http import HttpRequest
from dotenv.main import load_dotenv

logger = logging.getLogger(__name__)

load_dotenv()

BASE_DIR = Path(__file__).resolve().parent.parent.parent

SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY")

IS_RUNNING_TESTS = "test" in sys.argv

ALLOWED_HOSTS = os.environ.get("DJANGO_ALLOWED_HOSTS").split(",")

INTERNAL_IPS = os.environ.get("DJANGO_INTERNAL_IPS").split(",")

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # DRF
    "rest_framework",
    "rest_framework.authtoken",
    # Celery
    "django_celery_beat",
    "django_celery_results",
    # HTMX
    "django_htmx",
    # Auth
    "oauth2_provider",
    "social_django",
    # Apps
    "apps.my_auth.apps.MyAuthConfig",
    "apps.device.apps.DeviceConfig",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

SECURE_CROSS_ORIGIN_OPENER_POLICY = "same-origin-allow-popups"

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "social_django.context_processors.backends",
                "social_django.context_processors.login_redirect",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"

# Database
logger.debug("postgres")
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.environ.get("POSTGRES_DB"),
        "USER": os.environ.get("POSTGRES_USER"),
        "PASSWORD": os.environ.get("POSTGRES_PASSWORD"),
        "HOST": os.environ.get("POSTGRES_HOST"),
        "PORT": os.environ.get("POSTGRES_PORT"),
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.TokenAuthentication",
        "rest_framework.authentication.BasicAuthentication",
    ]
}

AUTHENTICATION_BACKENDS = (
    "social_core.backends.telegram.TelegramAuth",
    "django.contrib.auth.backends.ModelBackend",
)

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Create directory

STATIC_URL = "/static/"
STATIC_ROOT = os.path.join(BASE_DIR, "static")
if not os.path.exists(STATIC_ROOT):
    logger.info("Creating static directory")
    os.makedirs(STATIC_ROOT)


static_dirs = os.path.join(BASE_DIR, "staticfiles")
STATICFILES_DIRS = [static_dirs]
if not os.path.exists(static_dirs):
    logger.info("Creating staticfiles directory")
    os.makedirs(static_dirs)

MEDIA_URL = "media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")
if not os.path.exists(MEDIA_ROOT):
    logger.info("Creating media directory")
    os.makedirs(MEDIA_ROOT)

media_download = os.path.join(MEDIA_ROOT, "downloads")
if not os.path.exists(media_download):
    logger.info("Creating media/download directory")
    os.makedirs(media_download)

media_upload = os.path.join(MEDIA_ROOT, "uploads")
if not os.path.exists(media_upload):
    logger.info("Creating media/uploads directory")
    os.makedirs(media_upload)

if not os.path.exists(BASE_DIR.parent / "log"):
    os.makedirs(BASE_DIR.parent / "log")


LOGIN_REDIRECT_URL = "device:home"
LOGOUT_REDIRECT_URL = "my_auth:login"
LOGIN_URL = "my_auth:login"

# SOCIAL_AUTH
SOCIAL_AUTH_JSONFIELD_ENABLED = True
SOCIAL_AUTH_URL_NAMESPACE = "social"
SOCIAL_AUTH_TELEGRAM_BOT_TOKEN = os.environ.get("TELEGRAM_BOT_TOKEN")
TELEGRAM_BOT_NAME = os.environ.get("TELEGRAM_BOT_NAME")
TELEGRAM_BOT_TOKEN = os.environ.get("TELEGRAM_BOT_TOKEN")
# TELEGRAM_LOGIN_REDIRECT_URL = os.environ.get("TELEGRAM_LOGIN_REDIRECT_URL")

# celery setting.
CELERY_BROKER_URL = os.environ.get("CELERY_BROKER_URL")
CELERY_RESULT_BACKEND = os.environ.get("CELERY_RESULT_BACKEND")
CELERY_CACHE_BACKEND = "default"
CELERY_BEAT_SCHEDULER = "django_celery_beat.schedulers:DatabaseScheduler"
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True
CELERY_TIMEZONE = "UTC"
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 60 * 60

# Пауза между запросами для fgis.arshin
TIMEOUT_BETWEEN_REQUEST_TO_ARSHIN = 1
TIMEOUT_FOR_REQUEST_TO_ARSHIN = 3

# Heades table for frontend
HEADERS_ADDRESS = {
    "id": "№",
    "customer": "Абонент",
    "address": "Адрес",
    "itp": "ИТП",
    "tso": "ТCO",
    "service_organization": "ОО",
}
HEADERS_DEVICE = {
    "id": "№ п/п",
    "installation_point": "Место установки",
    "registry_number": "№ в реестре",
    "type": "Тип",
    "modification": "Модификация",
    "factory_number": "Зав. №",
    "valid_date": "Поверка до",
    "notes": "Примечание",
}
HEADERS_VERIFICATION = {
    "org_title": "Поверитель",
    "mit_number": "№ в реестре",
    "mit_notation": "Тип",
    "mi_modification": "Модификация",
    "mi_number": "Зав. №",
    "verification_date": "Дата поверки",
    "valid_date": "Поверка до",
    "is_actual": "Актуальна",
}
HEADERS_VERIFICATION_UPDATE = HEADERS_VERIFICATION.copy()
HEADERS_VERIFICATION_UPDATE.update(
    {
        "is_published": "Показывать",
        "empty": "",
        "delete": "Удалить",
    }
)
# File field names for csv
FIELDNAMES_FILE_MU = [
    "Наименование абонента",
    "Город",
    "Наименование улицы",
    "Тип улицы",
    "№ дома",
    "Корп",
    "Лит",
    "ТЦ",
    "Труба",
    "Тип",
    "Ду",
    "Номер",
    "Дата",
    "МПИ",
    "ТСО",
    "№ Тотэм",
]
FIELDNAMES_FILE_TYPE = ["Тип", "Номер в госреестре", "Наименование СИ"]
