# Generated by Django 5.1.1 on 2024-11-30 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("device", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="deviceverification",
            name="mi_mititle",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="deviceverification",
            name="mi_mitype",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="deviceverification",
            name="mi_modification",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="deviceverification",
            name="mi_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="deviceverification",
            name="mit_mitnumber",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="deviceverification",
            name="org_title",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
