# Generated by Django 5.1.1 on 2024-11-30 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("device", "0002_deviceverification_mi_mititle_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="deviceverification",
            name="organization",
        ),
    ]
