# Generated by Django 5.0.7 on 2024-08-12 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("device", "0003_meteringunit_totem_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="ITP",
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="address",
            name="city",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="address",
            name="corp",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="address",
            name="liter",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="address",
            name="street",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
