# Generated by Django 5.0.7 on 2024-08-12 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("device", "0005_alter_address_itp_alter_address_city_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="address",
            options={"verbose_name_plural": "addresses"},
        ),
    ]
