# Generated by Django 5.0.7 on 2024-08-12 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("device", "0009_alter_device_device_mod_alter_device_device_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deviceverification",
            name="organization",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
