# Generated by Django 5.0.7 on 2024-08-18 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("device", "0010_alter_deviceverification_organization"),
    ]

    operations = [
        migrations.AddField(
            model_name="deviceverification",
            name="is_actual",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="deviceverification",
            name="device_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="verifications",
                to="device.device",
            ),
        ),
    ]
