# Generated by Django 5.1.4 on 2024-12-16 20:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("metering_unit", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="slug",
            field=models.SlugField(default="", max_length=100),
        ),
    ]
