# Generated by Django 5.1.4 on 2024-12-16 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metering_unit", "0002_organization_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="slug",
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
