FROM python:3.11.9-slim
LABEL authors="AlexeyInkov"

ENV PIP_DISABLE_PIP_VERSION_CHECK 1
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

WORKDIR code

RUN apt-get update -y && \
    apt-get install -y netcat && \
    pip install --upgrade pip && \
    pip install poetry

COPY poetry.lock pyproject.toml ./

RUN poetry config virtualenvs.create false && poetry install --no-interaction --no-root

COPY core /core

RUN chmod +x /code/core/entrypoint.sh

ENTRYPOINT ["/code/core/entrypoint.sh"]

